export type BulkSummary = {
  vinculado: number;
  documento: string;
  sellerName: string | null;
  cargo: string | null;
  empresa: string | null;
  saldoInicial: number;
  Nombres?: string | null;
  Cargo?: string | null;
  Base?: number;
  Raspe?: number;
  SaldoAnt?: number;
  Debito?: number;
  Credito?: number;
  NuevoSaldo?: number;
  Cartera?: number;
  Rechazados?: number;
  Aceptados?: number;
  PendientesCont?: number;
  Digitados?: number;
  Vtabnet?: number;
  CuadreWeb?: number;
  Anulados?: number;
  saldoFinal?: number;
  cartera?: number;
  phone?: string | null;
  hasContact?: boolean;
  isValidForDispatch?: boolean;
  validationReason?: string | null;
  ccosto?: string | number;
};

export type ReportResponse = {
  bulk?: boolean;
  mode?: string;
  cartera: Array<Record<string, unknown>>;
  CarteraInicial?: { SALDO_ANT?: number } | null;
  Seller?: {
    NOMBRES?: string;
    CCOSTO?: string;
    NOMBRECARGO?: string;
    DOCUMENTO?: string;
  } | null;
  base?: number | null;
  totalCarteras?: number;
  limit?: number;
  sentCount?: number;
  skippedCount?: number;
  dispatched?: Array<Record<string, unknown>>;
  failures?: Array<{ vinculado?: number; phone?: string; message?: string }>;
  phone?: string | null;
  hasContact?: boolean;
};
